### ISSUE TITLE
npm run build fails.

### ISSUE THREAD

**Issue by 0p3r4t0r** [kaos-game/kaos#1]
So I realize that the build script is a work in progress, so no worries.

1. I get an infinite loop when trying to build. Output:

```text
-----------------------------------------------------------
UPDATE: SUBMODULES
-----------------------------------------------------------

Updating submodules from remotes...done


Submodule Status (check hashes)
-------------------------------
-6d3c5573eb6539696ccdec9432c44bc91da00aae src/kaos-canvas
-ddf9515fa1a672b36f69573b75c21b0014028b1d src/kaos-server
-b7877e14aa0e294359711a2a67375bf8b0896233 src/kaos-website


Submodule Summary
-----------------
Proceed w/ build? (y/n): 
```

2. So if you run `git submodule init` and *then* run the necessary `npm ci` commands and finally `npm run build`, everything works.

3. From `git help submodule`...
> status [--cached] [--recursive] [--] [<path>...]
>           Show the status of the submodules. This will print the SHA-1 of the
>           currently checked out commit for each submodule, along with the
>           submodule path and the output of git describe for the SHA-1. **Each SHA-1
>           will possibly be prefixed with - if the submodule is not initialized**, +
>           if the currently checked out submodule commit does not match the SHA-1
>           found in the index of the containing repository and U if the submodule
>           has merge conflicts.

4. The output from 1. confirms that this is indeed the issue. From the update section
of `git help submodule`...

> update [--init] ...
> ...
> If the submodule is not yet initialized, and you just want to use the
>           setting as stored in .gitmodules, you can automatically initialize the
>           submodule with the --init option.

4. So the quickest solution is to add `--init` to line 65
`git submodule update --remote --merge --quiet` -->
`git submodule update --init --remote --merge --quiet`

5. The other alternative would be to check manually if the submodules are initialized and run `git submodule init` if necessary.

**Comment by bsuth** [comment]
resolved. thanks!
